version: 2

models:
  - name: product_unit_cost
    description: "archivo que nos da información sobre el coste unitario de cada producto"
    tags: ['seed']
    columns:
      - name: product_id
        description: "PK de la tabla de product, idenfica de manera única cada producto"

      - name: product_unit_cost
        description: "coste unitario de cada producto"